spring:

  datasource:
    driverClassName: org.postgresql.Driver

  jpa:
    show-sql: true
    database: POSTGRESQL
    hibernate:
      ddl-auto: create-drop
  sql:
    init:
      platform: postgres